/**
 * WHERE EVERY PIECE'S CONTRACT COMES FROM.
 *
 * The kit was first written with the Palate MCP configured and not connected, and nothing noticed.
 * Every `when`, every rule about what sits next to what, came out of one head, which is the exact
 * generic output the product exists to prevent. This file is the correction, and it is data rather
 * than prose so that a gate can hold it to account.
 *
 * THE RULE: every slug named here was READ, through a deep-read tool, in a survey the plugin's own
 * recorder wrote to disk. src/lib/kit-survey.json is that record, generated by
 * scripts/kit-survey-snapshot.mjs from build-manifest.json and never by hand. gate-kit-complete
 * fails any citation outside it, so a reference that was only seen in a search result, or never
 * seen at all, cannot appear as evidence for anything.
 *
 * WHAT A CITATION MEANS. A donor is a reference whose own section notes show the piece in use, with
 * the section named the way the library names it. A rule is a claim about when the piece works,
 * and the slugs beside it are the references whose notes state or demonstrate it. An `avoid` is a
 * named anti-pattern from those same notes. Nothing here is inferred from taste; where the library
 * says nothing, this file says nothing.
 *
 * Re-skinning still applies. The donors govern STRUCTURE and PLACEMENT, never surface: a piece
 * reads every colour, face and radius from the brand bridge in foundations.css.
 */

export interface KitDonor {
  slug: string;
  /** What the reference does with this piece, in the library's own section names. */
  note: string;
}

export interface KitRule {
  text: string;
  /** References whose notes state or demonstrate the rule. Every one must be in kit-survey.json. */
  slugs: string[];
}

export interface KitPieceGrounding {
  donors: KitDonor[];
  rules: KitRule[];
  avoid: KitRule[];
}

export const kitGrounding: Record<string, KitPieceGrounding> = {
  navigation: {
    donors: [
      { slug: "warby-parker", note: "Two-tier header: a promo ribbon with a persistent 'Book an exam' link, then a centred wordmark with product categories left and service items right, booking and the quiz given equal billing." },
      { slug: "block-renovation", note: "White fixed 88px bar, horizontal menu, one orange 'Get Started' pill right; the sticky bar is the only element on the page allowed a shadow." },
      { slug: "habito", note: "Quiet text nav with chevron dropdowns and a single black pill anchored far right." },
      { slug: "parsley-health", note: "Slim announcement strip above a deep-teal sticky nav with one white pill." },
      { slug: "linear", note: "Transparent over the hero, condenses and gains a faint surface on scroll; ~14px items that never compete with the hero." },
      { slug: "aesop", note: "Transparent header over the hero photograph that acquires the cream ground on scroll over 0.5s; a slide-out drawer on mobile." },
      { slug: "mercury", note: "Glass-blur dark nav over a light page; multi-column dropdown cards revealed on hover." },
      { slug: "sealed-home", note: "Audience-segmented menu (Contractors / Households / Programs) so each audience is routed to its own track." },
      { slug: "swillhouse", note: "Announcement bar above a transparent nav with MENU and VENUES left, RESERVATIONS right; the bar reappears as a sticky bottom strip on scroll." },
      { slug: "1rebel", note: "Marquee ticker bar above a sticky nav that is transparent over the hero and white on scroll." },
      { slug: "gymshark", note: "Slim announcement bar, then a white header with a centred wordmark and category mega-menus." },
      { slug: "webflow", note: "Announcement banner ('New for Enterprise') above a nav of Platform / Solutions / Resources / Pricing, with Log in, Contact Sales and Start for free on the right." },
      { slug: "crisp", note: "Pre-nav announcement banner for an AI feature launch, then a wordmark, six links, search, Log In and Start Free Trial." },
    ],
    rules: [
      { text: "One primary action in the bar, pinned right, and it is the only saturated colour on the page.", slugs: ["block-renovation", "habito", "parsley-health", "mercury", "warby-parker"] },
      { text: "Service actions get equal billing with categories, and the persistent booking link lives in the ribbon so it is one click away on every page.", slugs: ["warby-parker", "swillhouse", "barrys"] },
      { text: "An announcement strip above the bar is the normal place for a live offer or notice; it is one line, one link.", slugs: ["warby-parker", "parsley-health", "gymshark", "glossier", "swillhouse", "1rebel", "attentive"] },
      { text: "Transparent over the hero, then a surface on scroll; the bar must not compete with the hero.", slugs: ["aesop", "linear", "barrys", "1rebel"] },
      { text: "Where a business serves distinct audiences, the nav routes them to separate tracks rather than mixing them on one page.", slugs: ["sealed-home", "vivvi"] },
    ],
    avoid: [
      { text: "A mega-nav with no real suite behind it; size the nav to the real surface.", slugs: ["notion"] },
      { text: "Backdrop blur over a busy gradient or cream band directly beneath the bar; it smudges the colour.", slugs: ["mercury"] },
      { text: "Stacking a ticker, a modal and a widget on first view; one piece of first-view chrome, not three.", slugs: ["vivvi"] },
    ],
  },

  hero: {
    donors: [
      { slug: "block-renovation", note: "Full-bleed photograph of a real homeowner in a finished room, a bold trust headline set plainly over it, one orange pill." },
      { slug: "warby-parker", note: "Lifestyle photograph with the serif headline placed INSIDE the image lower-left, a filled pill plus an outline pill." },
      { slug: "aesop", note: "The photograph or looping video is the brand; exactly three typographic elements on it (eyebrow, H2, one outline CTA) and nothing else." },
      { slug: "attentive", note: "Full-bleed real-people photograph with the H1 over it, one word in an italic serif, dual CTAs." },
      { slug: "mercury", note: "Concise H1, functional subhead, an inline email-plus-pill control that reads as one next step, and an aspirational landscape photograph rather than a product screenshot." },
      { slug: "parsley-health", note: "Split hero: cream text column with a serif headline, 'Get started' and a row of trust badges beneath it, against a relaxed patient portrait." },
      { slug: "dropbox", note: "50/50 text and real product UI rendered enormous; one filled pill plus a text link." },
      { slug: "linear", note: "Short medium-weight headline strictly centred, two CTAs, over an animated dot-grid and a high-fidelity product capture." },
      { slug: "basecamp", note: "The hero IS the page: a conversational H1, bulleted prose nav and a full product screenshot." },
      { slug: "loom", note: "One big quote as the H1, a hero video thumbnail that doubles as the product demo, and a CTA pair because there are two adoption paths." },
      { slug: "re-bath", note: "A 'made easy' promise over lifestyle photography with a pinned free-consultation form card in the hero." },
      { slug: "barrys", note: "Condensed headline plus a studio-finder card (search, nearest studio, book) over a cinematic in-studio image." },
      { slug: "habito", note: "Giant rounded headline centred over a soft gradient, a small anchor pill beneath it, nothing else." },
      { slug: "setia-law", note: "A giant thin headline top-left with the right two-thirds of the viewport left empty." },
      { slug: "lanserring", note: "Full-bleed sepia photograph, the mark, the wordmark, a tagline and a vertical ENQUIRE label." },
      { slug: "lava-dental", note: "Leads with the feeling ('painless and with a smile') and a video preview, because fear rather than information is the barrier." },
      { slug: "crisp", note: "H1 with link-blue underline emphasis, one 'Get your AI Agent' action, a trust signal, and the real dashboard mockup with a video play overlay." },
      { slug: "mejuri", note: "Full-bleed hero portrait with 'JEWELRY YOU CAN LIVE IN' set low-left; photography supplies the scale and the colour, the type stays modest." },
    ],
    rules: [
      { text: "The headline states the promise plainly and the photograph does the trust; real people and real rooms, not renders.", slugs: ["block-renovation", "warby-parker", "attentive", "re-bath"] },
      { text: "A product shows its real UI at full fidelity; a service or a system the buyer builds on shows an aspirational photograph and never a product screenshot.", slugs: ["dropbox", "linear", "basecamp", "loom", "mercury"] },
      { text: "One call to action by default; a pair only when there are genuinely two paths, and then a filled pill beside an outline one.", slugs: ["aesop", "loom", "dropbox", "warby-parker"] },
      { text: "Where the buyer is anxious or the job is booking, the next step sits inside the hero: a form card, a finder, an inline capture.", slugs: ["re-bath", "barrys", "mercury", "pilot-accounting"] },
      { text: "Trust lands directly under the CTA or directly under the hero.", slugs: ["parsley-health", "warby-parker", "attentive"] },
      { text: "For a fear-laden service, lead with the feeling and the process, not with services or credentials.", slugs: ["lava-dental", "re-bath"] },
    ],
    avoid: [
      { text: "A dual CTA on a single-product client; it dilutes the click.", slugs: ["dropbox", "webflow"] },
      { text: "A stylised mock where the real screenshot is the trust signal.", slugs: ["loom", "dropbox"] },
      { text: "Emptiness without campaign-grade photography; it reads as half-built.", slugs: ["glossier", "lanserring"] },
      { text: "A three-card multi-path hero on a product with one path.", slugs: ["webflow"] },
    ],
  },

  trust: {
    donors: [
      { slug: "warby-parker", note: "A tight trust strip directly under the hero: free shipping, free returns, vision benefits accepted, first-order offer." },
      { slug: "attentive", note: "Customer logo strip placed directly under the hero so trust lands before any feature claim." },
      { slug: "pilot-accounting", note: "Client-logo social-proof strip of recognisable startup logos in the first fold." },
      { slug: "mercury", note: "'Loved by 300K+ of the most ambitious entrepreneurs' as a count-plus-character claim; explicitly not a logo wall in this category." },
      { slug: "dropbox", note: "A slim 246px social-proof band ('over 700 million registered users') as the breath between hero and features." },
      { slug: "loom", note: "'Millions of people across 400,000 companies' counted claim with a logo strip, right under the hero." },
      { slug: "habito", note: "'Rated 4.9 out of 5' with testimonials before the close." },
      { slug: "lovevery", note: "A star rating overlaid on the hero, then ratings, reviews and 'happy families' numbers." },
      { slug: "parsley-health", note: "Trust badges under the hero CTA, a measurable-outcome percentage, and an 'As Seen In' press row." },
      { slug: "greenwise-organic-lawn-care", note: "'Why Choose Greenwise?' reassurance band with icon reasons: organic, family and pet safe, established since 2007." },
      { slug: "sealed-home", note: "A named certification ('first Energy Star Home Upgrade Service Provider') as the credibility marker, placed early." },
      { slug: "avalon-accounting", note: "An endorsement band of three circular partner and award badge icons under a kicker ('Like Two Peas in a Pod'); the Xero Platinum-partner claim is its own 50/50 split above it." },
      { slug: "barrys", note: "'8+ Million Strong' community band before the closing CTA." },
      { slug: "webflow", note: "Customer logo strip in tiny uppercase directly under the hero." },
    ],
    rules: [
      { text: "Trust lands immediately under the hero, before any feature claim.", slugs: ["attentive", "warby-parker", "pilot-accounting", "loom", "dropbox"] },
      { text: "Choose the form by what THIS buyer recognises: logos only when they are known to the audience, otherwise a count plus a character claim, an accreditation, a partner badge or a rating.", slugs: ["mercury", "pilot-accounting", "habito", "sealed-home", "avalon-accounting"] },
      { text: "A slim band is enough; it is a breath between the hero and the argument, not a section.", slugs: ["dropbox", "warby-parker"] },
      { text: "A figure needs a source and a scale the brand actually has.", slugs: ["dropbox", "mercury", "parsley-health"] },
    ],
    avoid: [
      { text: "Borrowed-confidence numbers ('700M users') on a brand without the scale.", slugs: ["dropbox"] },
      { text: "A logo wall in a regulated or aspirational category.", slugs: ["mercury"] },
      { text: "Proof you cannot back; drop the section rather than pad it.", slugs: ["parsley-health"] },
    ],
  },

  problem: {
    donors: [
      { slug: "pilot-accounting", note: "Problem framing ('the cost of being buried in bookkeeping') immediately after the logo strip, before the offer." },
      { slug: "parsley-health", note: "A differentiation beat ('Finally, a doctor that asks why') right after the hero." },
      { slug: "re-bath", note: "A 'made easy' promise first for an anxious buyer, and Results galleries of before-and-afters as the outcome proof." },
      { slug: "anthropic", note: "A full-width mission band carrying one statement of purpose with no CTA at all." },
      { slug: "mercury", note: "A brand-voice positioning block that speaks to the buyer's identity rather than the product." },
      { slug: "avalon-accounting", note: "A 50/50 mission and values split with a photograph, no CTA." },
      { slug: "swillhouse", note: "An About block of two lead paragraphs in a narrow measure with enormous whitespace; the quietest section on the page." },
      { slug: "lanserring", note: "A plain brand statement ('We are Lanserring, providers of...') paired with a photograph, then the founders' story in two acts." },
      { slug: "dishoom", note: "The do/don't sells the place, heritage and feeling first, then makes menus and booking effortless (the pages layer is empty; this is grounded in the do/don't)." },
      { slug: "setia-law", note: "About: a kicker, a two-line heading left, body right, then a text link." },
      { slug: "unoit", note: "A centred positioning paragraph on a faint grey panel directly after the concept hero." },
      { slug: "sealed-home", note: "A one-line positioning statement and later a one-line vision statement between feature sections." },
      { slug: "plausible", note: "'It's time to ditch Google Analytics' comparative pitch, with the vs-competitor comparison pages carried in the nav dropdown." },
    ],
    rules: [
      { text: "Name the buyer's problem right after trust and before any feature.", slugs: ["pilot-accounting", "parsley-health", "re-bath"] },
      { text: "A statement band carries one idea on its own ground and carries no call to action; that absence is what lets it land.", slugs: ["anthropic", "avalon-accounting", "swillhouse", "mercury", "sealed-home"] },
      { text: "Story sells the place and the feeling before any action, and the narrative is the differentiator; keep it.", slugs: ["dishoom", "lanserring", "swillhouse"] },
      { text: "The positioning paragraph must say something specific; a striking hero over filler wastes the impression.", slugs: ["unoit"] },
      { text: "Before-and-after is an outcome gallery and every image must be the client's own.", slugs: ["re-bath", "lava-dental"] },
    ],
    avoid: [
      { text: "Leading with company history or a wall of services when the buyer is anxious.", slugs: ["re-bath", "lava-dental"] },
      { text: "A call to action inside the mission band.", slugs: ["anthropic"] },
      { text: "Copying the literary voice rather than calibrating a similar warmth in the client's own words.", slugs: ["dishoom"] },
    ],
  },

  benefits: {
    donors: [
      { slug: "block-renovation", note: "'Why homeowners choose Block' benefit cards at 8px and 16px radii on warm surfaces." },
      { slug: "greenwise-organic-lawn-care", note: "'Why Choose Greenwise?' reassurance band with icon reasons." },
      { slug: "linear", note: "The repeated unit: heading, one short subhead, a product panel as proof, identical in every capability block." },
      { slug: "notion", note: "Two alternating-row capability sections between the hero and the proof." },
      { slug: "dropbox", note: "Three to five equal-height feature sections, each a two-clause H2 ending in a period, plus one tall depth section." },
      { slug: "wealthsimple", note: "One product per act on alternating sand and off-white grounds, each revealing calmly on scroll." },
      { slug: "attentive", note: "Feature deep-dives, each text plus a preview card on a photographic backdrop." },
      { slug: "pilot-accounting", note: "Feature acts on alternating white, grey and violet grounds." },
      { slug: "avalon-accounting", note: "'What We Do': a two-column grid of five pastel service cards, each with a line icon and a 'Learn more' link." },
      { slug: "webflow", note: "Capability deep-dive split into sub-blocks (Design, Content, Hosting, Optimisation)." },
      { slug: "unoit", note: "Services as clean expandable rows; the note says the usable list underneath is why the concept hero works." },
      { slug: "lava-dental", note: "Services on a pale-mint band: one feature card plus a four-up row of numbered service cards." },
      { slug: "vivvi", note: "'The Vivvi Difference': a centred heading introducing soft benefit cards, on alternating warm and white bands." },
    ],
    rules: [
      { text: "Repeat one section anatomy identically so a long page stays calm and scannable.", slugs: ["linear", "dropbox", "wealthsimple", "webflow"] },
      { text: "Alternate grounds to chapter the run; the colour switch is the divider.", slugs: ["parsley-health", "warby-parker", "wealthsimple", "pilot-accounting", "1rebel"] },
      { text: "Cards where the proof is a claim; the alternating row where the proof is an image or the product.", slugs: ["block-renovation", "notion", "attentive"] },
      { text: "Swap the product panel for the client's real proof, an outcome, a photograph, a case, when the proof is not an interface.", slugs: ["linear"] },
      { text: "Where the offer is a list of services, make it genuinely browsable: expandable rows or a plain grid with one link each.", slugs: ["unoit", "avalon-accounting", "lava-dental"] },
    ],
    avoid: [
      { text: "A dark UI panel in every section when the client's proof is outcomes rather than interface.", slugs: ["linear"] },
      { text: "Thirteen sections without thirteen differentiated stories; six to eight is the right depth for most.", slugs: ["dropbox", "mercury"] },
      { text: "The density of a national retailer on a single practice: three to five bands.", slugs: ["warby-parker", "wealthsimple"] },
    ],
  },

  demo: {
    donors: [
      { slug: "dropbox", note: "Real product UI rendered enormous, one product narrative per section." },
      { slug: "linear", note: "A high-fidelity product capture in the hero and a dark product panel as proof in every capability block." },
      { slug: "basecamp", note: "A full Basecamp 5 product screenshot composed as the page itself." },
      { slug: "loom", note: "The hero video thumbnail is the demo; the note says a real recording, not a stylised mock, is the trust signal." },
      { slug: "webflow", note: "A three-card entry hero (AI / Template / Scratch) that mirrors the product's own onboarding paths, each with its UI preview." },
      { slug: "crisp", note: "A real dashboard mockup with a video play overlay in the hero, then feature deep-dives each with a UI mockup." },
      { slug: "plausible", note: "A real dashboard mockup with macOS traffic-light dots." },
      { slug: "pitch", note: "Product screenshot in the hero, then a numbered walkthrough where each step carries its own screenshot." },
      { slug: "lanserring", note: "A video introduction section ('Watch Now') after the brand statement." },
      { slug: "lava-dental", note: "A video preview inside the hero." },
    ],
    rules: [
      { text: "Show the real thing at full fidelity; never a stylised render.", slugs: ["dropbox", "loom", "basecamp", "linear", "crisp", "plausible"] },
      { text: "A demo entry point mirrors the product's own first step, one card per genuine path.", slugs: ["webflow"] },
      { text: "A video preview carries a real still, a stated length and a fallback that works when the video cannot.", slugs: ["loom", "lanserring", "lava-dental"] },
    ],
    avoid: [
      { text: "Decorative motion that does not demonstrate the product; every animation should justify itself as a demo.", slugs: ["webflow", "pitch"] },
      { text: "A product screenshot in the hero of a brand selling a system rather than a tool.", slugs: ["mercury"] },
      { text: "Multiplayer cursors, sparkles or a multi-path hero on a product that does not have them.", slugs: ["pitch", "webflow"] },
    ],
  },

  process: {
    donors: [
      { slug: "habito", note: "The proposition as numbered panels, each anchored by a solid black circular badge with a white numeral." },
      { slug: "re-bath", note: "'Our Bathroom Remodel Process': a clear, named step-by-step; the note calls it the anxiety-killer." },
      { slug: "parsley-health", note: "'Your Complete Care journey': a six-step process as a carousel of cards." },
      { slug: "mercury", note: "'Apply online in 10 minutes': a process explainer with a step list and an illustrated visual." },
      { slug: "lanserring", note: "'Our Process: Design-led or Production-led' with a 'See How We Work' link." },
      { slug: "pitch", note: "'How Pitch works': four numbered steps, each its own block with eyebrow, headline, paragraph and screenshot." },
      { slug: "sealed-home", note: "A how-it-works explainer of the rebate and measurement workflow." },
      { slug: "lava-dental", note: "The process as a circular arc-timeline with the promise at its centre, made to feel calm and contained." },
    ],
    rules: [
      { text: "Number the steps and anchor each with a badge, one step per panel.", slugs: ["habito", "pitch"] },
      { text: "The process de-mystifies the scary part; on a high-anxiety service it is never hidden and never below the fold of the argument.", slugs: ["re-bath", "lava-dental", "parsley-health"] },
      { text: "Put a real figure on time where one exists.", slugs: ["mercury"] },
    ],
    avoid: [
      { text: "A numbered walkthrough for a product with no true linear flow.", slugs: ["pitch"] },
      { text: "A clinical step-list where the sequence needs to feel calm; the framing carries as much as the steps.", slugs: ["lava-dental"] },
    ],
  },

  usecases: {
    donors: [
      { slug: "sealed-home", note: "Audience-segmented nav and CTAs (Contractors / Households / Programs); one audience per page." },
      { slug: "dropbox", note: "An industry grid of 3x2 photograph cards (Construction, Media, Technology...), each with a lede and 'Learn more'." },
      { slug: "loom", note: "'Video messaging for all use cases': an inventory that lets the buyer find themselves." },
      { slug: "lovevery", note: "An age-band selector that filters a grid of real kits." },
      { slug: "warby-parker", note: "A multi-step style quiz as the primary hero CTA." },
      { slug: "bellroy", note: "'Find a setup for any trip': a themed collection row by use case." },
      { slug: "block-renovation", note: "'No matter your project, we can help': segmentation by project type before lead capture." },
      { slug: "pitch", note: "'A tool for the whole team': multi-audience positioning block." },
      { slug: "vivvi", note: "One nav item (For Employers) kept visually distinct to serve a second audience without a second site." },
      { slug: "unoit", note: "Services as clean expandable rows (Hair & Styling, Beard & Shave, Colour, Skin), the 'experience menu', directly after the positioning paragraph." },
    ],
    rules: [
      { text: "Let the buyer find themselves, then route them; the page does not try to serve every audience at once.", slugs: ["loom", "sealed-home", "vivvi"] },
      { text: "A selector that filters real options beats a list of segments.", slugs: ["lovevery", "warby-parker"] },
      { text: "Each card is a router to a real page; the grid is navigation, not a claim.", slugs: ["dropbox", "block-renovation", "bellroy"] },
    ],
    avoid: [
      { text: "Mixing audiences within one page the way generic templates do.", slugs: ["sealed-home"] },
      { text: "Generic stock photography on industry cards; it makes the grid read as a template.", slugs: ["dropbox"] },
    ],
  },

  testimonials: {
    donors: [
      { slug: "sealed-home", note: "One strong contractor quote pulled onto a blue panel." },
      { slug: "avalon-accounting", note: "'Those Who Trust Us': a carousel showing one card at a time, client photo, pull-quote, attribution and a case-study link." },
      { slug: "habito", note: "A rating plus testimonials placed before the close, then a low-pressure capture." },
      { slug: "parsley-health", note: "A named five-star testimonial early, and member video testimonials later." },
      { slug: "pilot-accounting", note: "Testimonials and case proof in a carousel before the demo CTA." },
      { slug: "lovevery", note: "Ratings, reviews and 'happy families' numbers as the social-proof section." },
      { slug: "wealthsimple", note: "A trust act ('Trusted by over 4 million Canadians') directly before the final CTA." },
      { slug: "warby-parker", note: "'Warby Parker in the wild': a lifestyle social-proof band." },
      { slug: "lava-dental", note: "'Our patients' smiles speak for themselves': results as social proof." },
      { slug: "plausible", note: "'People love Plausible': customer logos and testimonials as one section." },
    ],
    rules: [
      { text: "One strong quote with a real attribution beats many weak ones; the attribution is the proof.", slugs: ["sealed-home", "avalon-accounting"] },
      { text: "Proof sits after the argument and before the close.", slugs: ["habito", "parsley-health", "wealthsimple", "barrys", "pilot-accounting"] },
      { text: "Pair the quote with a case link or a rating wherever either exists.", slugs: ["avalon-accounting", "habito"] },
      { text: "A video testimonial is a real person, a real still and their own words transcribed.", slugs: ["parsley-health"] },
    ],
    avoid: [
      { text: "Leading with the proof before the argument; the single CTA is repeated only after the evidence.", slugs: ["parsley-health"] },
      { text: "Community or count claims the brand cannot substantiate.", slugs: ["dropbox", "mercury"] },
    ],
  },

  casestudies: {
    donors: [
      { slug: "anthropic", note: "One headline project given the entire visual stage on a dark mode-flip, then a three-card releases grid." },
      { slug: "lanserring", note: "'Selected Projects' gallery on the home page pushing depth to project pages." },
      { slug: "re-bath", note: "Results galleries and before-and-afters as inner pages; 'Design Styles' as a gallery wall on the home page." },
      { slug: "setia-law", note: "An insights carousel: photograph left, kicker, headline, excerpt and 'Read article' right." },
      { slug: "avalon-accounting", note: "A case-study link from each testimonial card." },
      { slug: "dropbox", note: "A customer study as the editorial closer before the footer." },
      { slug: "attentive", note: "'Real results from leading brands': customer cards." },
      { slug: "pitch", note: "'Built with Pitch': a gallery of work made with the product as social proof." },
      { slug: "mercury", note: "A quantitative flex ('$650M in annual revenue and profitable') only because the numbers genuinely flex." },
      { slug: "parsley-health", note: "Outcomes band, 'Results you can measure. Progress you can feel.', a single percentage stat paired with its claim." },
    ],
    rules: [
      { text: "Give one story the whole stage and list the rest as a grid.", slugs: ["anthropic", "lanserring"] },
      { text: "Figures come from the customer's own records, with the customer named and consenting.", slugs: ["mercury", "dropbox"] },
      { text: "A card is a router to a full page, not the story itself.", slugs: ["lanserring", "setia-law", "re-bath"] },
    ],
    avoid: [
      { text: "A quantitative flex without the numbers behind it.", slugs: ["mercury"] },
      { text: "A stock case-study grid with no through-line.", slugs: ["lanserring"] },
    ],
  },

  pricing: {
    donors: [
      { slug: "parsley-health", note: "Two clearly priced program cards ('from $150/mo', '$350-$550'); the note says never bury the price." },
      { slug: "pilot-accounting", note: "Service tiers (Bookkeeping, SMB Booster, Tax) presented as product cards." },
      { slug: "posthog", note: "Transparent, usage-based pricing as its own home-page section." },
      { slug: "plausible", note: "A pricing teaser ('Traffic based plans that match your growth') before the closing CTA." },
      { slug: "mercury", note: "A bordered pricing tier card with plan name, price and feature list." },
      { slug: "warby-parker", note: "A price hook in the promo ribbon ('starting at $95')." },
      { slug: "lava-dental", note: "'Price list, invest in your smile': transparent pricing framed as reassurance about cost." },
      { slug: "block-renovation", note: "'See contractors and costs near you' and 'Start planning your renovation for free' as the quote path." },
      { slug: "caliber", note: "The do/don't puts 'Online Estimate' and 'Book an Appointment' front and centre as the primary navigation actions; the quote path IS the product." },
      { slug: "greenwise-organic-lawn-care", note: "'Request a Quote' in the utility bar and a quote form as the close." },
      { slug: "re-bath", note: "A free design consultation form pinned in the hero as the quote path." },
    ],
    rules: [
      { text: "Surface the price where the purchase is high-trust; cost mystery is a conversion leak and price is part of the reassurance.", slugs: ["parsley-health", "lava-dental", "posthog"] },
      { text: "Where the price cannot be listed, make the quote or estimate path the primary action.", slugs: ["caliber", "block-renovation", "greenwise-organic-lawn-care", "re-bath"] },
      { text: "Tiers read as product cards.", slugs: ["pilot-accounting", "parsley-health", "mercury"] },
    ],
    avoid: [
      { text: "Hidden pricing on a high-trust purchase.", slugs: ["parsley-health"] },
      { text: "A bank-scale product ticker or comparison table on a local adviser.", slugs: ["wealthsimple"] },
    ],
  },

  comparison: {
    donors: [
      { slug: "parsley-health", note: "A comparison table against Traditional PCP, DTC labs and concierge clinics, placed after the proof and before the FAQ." },
      { slug: "wealthsimple", note: "A classic-portfolio comparison table; the note says to drop it for a local adviser." },
      { slug: "plausible", note: "'It's time to ditch Google Analytics': a comparative pitch as its own section, with a comparison-page taxonomy in the nav." },
    ],
    rules: [
      { text: "Compare against the real alternatives the buyer is weighing, and say who wrote it and when.", slugs: ["parsley-health", "plausible"] },
      { text: "Only with genuine substance; a comparison without it reads as padding.", slugs: ["parsley-health", "wealthsimple"] },
    ],
    avoid: [
      { text: "Naming a competitor to ditch unless the brand voice supports confrontation.", slugs: ["plausible"] },
      { text: "Comparison-table scale that only makes sense for a full product suite.", slugs: ["wealthsimple"] },
    ],
  },

  faq: {
    donors: [
      { slug: "parsley-health", note: "A seven-question FAQ accordion placed after the comparison and before the final CTA; conditions as expandable accordion categories." },
      { slug: "lava-dental", note: "'Before you start, you might want to know more': the FAQ framed as pre-emptive reassurance, after price and before contact." },
      { slug: "habito", note: "FAQs and a help centre as an inner destination the home page routes to." },
      { slug: "unoit", note: "Services as expandable rows: the accordion used for scope rather than for questions." },
    ],
    rules: [
      { text: "The FAQ sits after the evidence and before the final call to action.", slugs: ["parsley-health", "lava-dental"] },
      { text: "Frame it as removing the unknowns that cause anxiety, not as a pitch in question form.", slugs: ["lava-dental"] },
      { text: "Accordion for scope; visible answers for the few questions everyone asks.", slugs: ["parsley-health", "unoit"] },
    ],
    avoid: [
      { text: "Burying the FAQ on an inner page when it is the anxiety-removing beat on the home page.", slugs: ["lava-dental"] },
    ],
  },

  cta: {
    donors: [
      { slug: "mercury", note: "The final CTA echoes the hero's inline email-plus-pill pattern." },
      { slug: "parsley-health", note: "'Ready for a different kind of care?' repeating the single 'Get started' only after the evidence." },
      { slug: "notion", note: "'Try for free': short, direct, friendly closing CTA." },
      { slug: "block-renovation", note: "'Renovate confidently': a confident closing CTA after the funnel." },
      { slug: "greenwise-organic-lawn-care", note: "'Ready to Transform Your Outdoor Space?': the quote form as the close." },
      { slug: "wealthsimple", note: "A trust statement plus a single dark pill as the final act." },
      { slug: "barrys", note: "'Join the hustle' after the community proof band." },
      { slug: "attentive", note: "'Ready to make every message more personal?' as the closing section." },
      { slug: "swillhouse", note: "Two full-width CTA tiles (Reservations, Giftcards) over photography mid-page, and a private-events band later." },
      { slug: "unoit", note: "'We're ready when you are': a warm closing booking CTA." },
      { slug: "webflow", note: "An enterprise CTA echo before the closing CTA." },
      { slug: "crisp", note: "A sticky bottom CTA bar carrying the brand icon, on a short five-section page." },
    ],
    rules: [
      { text: "One closing action, echoing the hero's.", slugs: ["mercury", "parsley-health", "wealthsimple", "attentive"] },
      { text: "Close with proof beside the action where the brand has real numbers.", slugs: ["wealthsimple", "barrys"] },
      { text: "A mid-page banner is one line and one action for the reader already convinced.", slugs: ["swillhouse", "block-renovation"] },
      { text: "Keep the CTA the obvious next step on every screen without letting a friendly tone bury it.", slugs: ["habito"] },
    ],
    avoid: [
      { text: "A call to action inside a statement or mission band.", slugs: ["anthropic"] },
      { text: "Leading with the final CTA before the evidence.", slugs: ["parsley-health"] },
      { text: "Replacing an inline capture with 'Get a demo' where signup is the real next step.", slugs: ["mercury"] },
    ],
  },

  forms: {
    donors: [
      { slug: "re-bath", note: "'Schedule Your Free Design Consultation' as a pinned form card in the hero; conversion stays available throughout." },
      { slug: "greenwise-organic-lawn-care", note: "'Check Service Availability': an address form that confirms coverage then routes to a quote; a quote form as the close." },
      { slug: "mercury", note: "An inline email input joined to a pill so the two read as one composite control." },
      { slug: "pilot-accounting", note: "Email capture plus a violet CTA inside the hero." },
      { slug: "block-renovation", note: "'Start planning your renovation for free' lead capture early; forms post to an API with toast feedback." },
      { slug: "avalon-accounting", note: "'Let's Get Started': a contact section with underline-style inputs and a pill submit; a newsletter modal with topic checkboxes." },
      { slug: "habito", note: "A low-pressure newsletter block with an email field and interest checkboxes in place of a hard sell." },
      { slug: "aesop", note: "A minimal cream-on-cream newsletter form with one email input and an outline button." },
      { slug: "warby-parker", note: "A multi-step style quiz off the hero, email capture in the footer." },
      { slug: "barrys", note: "Studio finder in the hero with search, nearest studio and book." },
      { slug: "parsley-health", note: "Membership signup and insurance verification as the conversion path; newsletter in the footer." },
      { slug: "dishoom", note: "'Book a table' and per-venue menus threaded through the narrative so booking never feels transactional; the do/don't warns against stripping the story to a bare reservation funnel." },
    ],
    rules: [
      { text: "Capture early and keep the form reachable throughout.", slugs: ["block-renovation", "re-bath"] },
      { text: "Ask the smallest thing first, an email, a postcode, an address, and personalise after.", slugs: ["mercury", "greenwise-organic-lawn-care", "pilot-accounting"] },
      { text: "A newsletter is low-pressure and never the close.", slugs: ["habito", "aesop"] },
      { text: "Booking-first where the business runs on appointments or classes.", slugs: ["barrys", "warby-parker", "myodetox"] },
    ],
    avoid: [
      { text: "Vendor chat or booking widgets treated as if they were the brand.", slugs: ["attentive", "habito"] },
      { text: "A hard sell at the close where a soft capture is the reference's whole manner.", slugs: ["habito"] },
    ],
  },

  footer: {
    donors: [
      { slug: "anthropic", note: "A slate footer that weighs as much as the hero, with the oversized wordmark bottom-left as the page's exhale." },
      { slug: "aesop", note: "A full-bleed charcoal footer, link columns and the brand mark, the only place pure white appears on text; the newsletter is its own block just before it." },
      { slug: "mercury", note: "An inset white footer that is deliberately NOT mode-flipped, with regulatory disclosures." },
      { slug: "parsley-health", note: "A deep-teal footer with link columns, centres, social, newsletter and the clinical legal links a medical brand requires." },
      { slug: "greenwise-organic-lawn-care", note: "Services, service areas and per-region contact in the footer." },
      { slug: "block-renovation", note: "Routes services and per-city pages; the note says drop the trackers." },
      { slug: "avalon-accounting", note: "A dark footer with the wordmark, social icons and a multi-column link grid." },
      { slug: "swillhouse", note: "Four columns: subscribe form, sitemap, a book-a-table venue selector, social." },
      { slug: "gymshark", note: "Link columns, newsletter, app, region and social." },
      { slug: "habito", note: "The newsletter block above the legal and link rows." },
      { slug: "warby-parker", note: "A large multi-column retail footer with email capture and social on a tidy white anchor." },
    ],
    rules: [
      { text: "Decide the mode-flip deliberately: a dark footer closes a light page; an inset same-ground footer suits a page that already alternates.", slugs: ["anthropic", "aesop", "mercury"] },
      { text: "Carry the practical: contact per location, service areas, and the legal a regulated brand needs.", slugs: ["greenwise-organic-lawn-care", "parsley-health", "mercury"] },
      { text: "The oversized wordmark sits at the bottom of the footer as the page's exhale.", slugs: ["anthropic"] },
      { text: "A newsletter block beside or above the footer's legal and link rows.", slugs: ["aesop", "habito"] },
    ],
    avoid: [
      { text: "A footer that is a link dump rather than organised columns.", slugs: ["aesop"] },
      { text: "Third-party trackers riding along with the footer.", slugs: ["block-renovation"] },
      { text: "Flipping the footer where the reference's page relies on continuity.", slugs: ["mercury"] },
    ],
  },

  locality: {
    donors: [
      { slug: "greenwise-organic-lawn-care", note: "'Our Service Area': region cards with per-region phones and embedded maps, then 'Check Service Availability', an address form that confirms coverage and routes to a quote." },
      { slug: "block-renovation", note: "'See contractors and costs near you' finder, then a 50-state city grid of compact link cards." },
      { slug: "re-bath", note: "'Find Your Local Re-Bath': a postcode locator over a faint map, placed after the trust band." },
      { slug: "barrys", note: "A studio-finder card inside the hero: search, nearest studio, book." },
      { slug: "aesop", note: "'Find a store': a city list with a CTA to the full locator." },
      { slug: "parsley-health", note: "Centres (NYC / LA / Virtual) listed in the footer." },
      { slug: "unoit", note: "A Locations section before the closing booking CTA, each shop with its own page." },
      { slug: "lava-dental", note: "'We are right here': contacts and a map as the close." },
      { slug: "vivvi", note: "Campuses as location pages and social proof by families and locations." },
      { slug: "myodetox", note: "The do/don't leads with the assessment as the headline product, then books by location." },
    ],
    rules: [
      { text: "Make locality concrete: named areas, per-area contact, then a coverage check before the buyer commits.", slugs: ["greenwise-organic-lawn-care", "re-bath", "block-renovation"] },
      { text: "The finder is a conversion surface; it sits where the decision is made, in the hero for booking, after trust for a quote.", slugs: ["barrys", "re-bath", "block-renovation"] },
      { text: "Every location gets its own page and the home page routes to it.", slugs: ["unoit", "vivvi", "block-renovation"] },
    ],
    avoid: [
      { text: "Reproducing the reference's service areas or locations; only the client's own.", slugs: ["greenwise-organic-lawn-care", "re-bath"] },
    ],
  },
};

/**
 * THE RHYTHMS. How the pieces sit together, read from the library's own "rhythm to borrow" notes
 * rather than invented. A rhythm that names ONE reference is that reference's own order (anthropic's
 * five acts). A rhythm that names several is a COMPOSITE of their notes, and every step names, in
 * parentheses, the reference(s) whose note states it; the gate refuses a step with no citation and
 * a citation outside the rhythm's own list, because two rhythms were once attributed to references
 * whose notes describe a different order. A composed page declares which rhythm it follows, and
 * the example pages are built to these exactly. Steps name kit pieces where one exists.
 */
export const kitRhythms: KitRhythm[] = [
  {
    id: "relief-through-process",
    name: "Relief through process",
    when: "A high-anxiety service: renovation, dental, legal, anything the buyer dreads.",
    steps: [
      "Hero with the 'made easy' promise and the next step in view: a pinned consultation form (re-bath) or an early lead capture (block-renovation)",
      "Trust or proof directly beneath (re-bath, block-renovation)",
      "Locality: find your local team (re-bath), contractors and costs near you (block-renovation)",
      "The service range (re-bath) or benefit cards (block-renovation)",
      "Aspirational outcome: design styles and a gallery (re-bath), real results (lava-dental)",
      "The named, numbered process that de-mystifies the scary part (re-bath, lava-dental)",
      "Transparent price, and an FAQ framed as reassurance (lava-dental)",
      "A confident closing call to action (block-renovation); contacts and a map as the close (lava-dental)",
      "Deep footer with the service tree and locations (re-bath)",
    ],
    slugs: ["re-bath", "block-renovation", "lava-dental"],
    caution: "Do not lead with history or a wall of services; the anxious buyer needs the promise and a clear next step first, and never hide the process (re-bath). Do not render the process as a clinical step-list; it works because it feels calm and contained (lava-dental).",
  },
  {
    id: "evidence-spine",
    name: "Evidence spine",
    when: "A high-trust, high-consideration purchase: medical membership, advisory, anything with credentials.",
    steps: [
      "Hero with trust badges under the CTA (parsley-health)",
      "Differentiation statement (parsley-health)",
      "The care or delivery journey as steps (parsley-health), or as a timeline that makes it feel contained (lava-dental)",
      "Named credentials and the real team (parsley-health, lava-dental)",
      "A measurable outcome (parsley-health); real results (lava-dental)",
      "Clearly priced cards (parsley-health); transparent price as reassurance (lava-dental)",
      "Testimonials and press (parsley-health)",
      "Head-to-head comparison (parsley-health)",
      "FAQ framed as reassurance, before the final CTA (parsley-health, lava-dental)",
      "The single CTA repeated, only now (parsley-health)",
    ],
    slugs: ["parsley-health", "lava-dental"],
    caution: "Nineteen sections is right for a medical membership, not a simple service. Keep the trust spine, drop any section you cannot back with evidence, and never bury the price (parsley-health).",
  },
  {
    id: "repeated-shape",
    name: "Repeated identical shape",
    when: "A product with several capabilities to show.",
    steps: [
      "Hero with real product proof (linear, dropbox)",
      "A slim social-proof band as the breath between hero and features: a counted claim (dropbox) or a logo strip (webflow)",
      "A run of capability sections with identical anatomy: heading, subhead, proof panel (linear, dropbox)",
      "One deeper, data-rich section (linear, dropbox)",
      "One warm closing block, then the CTA (linear); an enterprise CTA echo before the close (webflow)",
      "Dense organised footer (linear, dropbox, webflow)",
    ],
    slugs: ["linear", "dropbox", "webflow"],
    caution: "Show the UI in every section only if the UI is the proof; otherwise keep the shape and swap the panel for the client's real proof (linear). Six to eight sections unless there are genuinely more stories (dropbox).",
  },
  {
    id: "short-page-deep-nav",
    name: "Short page, deep nav",
    when: "A big product whose breadth belongs in the navigation, not the page.",
    steps: [
      "Hero with the argument and the product shown at full fidelity (notion, basecamp)",
      "Two alternating-row capability sections (notion)",
      "Proof (notion)",
      "A short, direct CTA (notion) or a closing tagline (basecamp)",
      "The breadth carried by the navigation: a deep mega-nav (notion) or a bulleted prose inventory of every page inside the hero (basecamp)",
    ],
    slugs: ["notion", "basecamp"],
    caution: "Works only when there is a real suite behind the nav; a single product copying it gets an empty mega-nav (notion). Do not pad the page with sections; the discipline is the brand (basecamp).",
  },
  {
    id: "buy-then-read",
    name: "Alternate buy and read",
    when: "Editorial commerce, a brand with things to say as well as sell.",
    steps: [
      "One photograph that is the brand (aesop, gymshark, mejuri)",
      "A product row immediately (aesop, gymshark)",
      "An editorial block to be read rather than scanned (aesop), or an inverted full-bleed image act (mejuri)",
      "Another product row (aesop, gymshark)",
      "A lower-commitment entry: gifting and samples (aesop)",
      "A stories row (aesop)",
      "Store finder and newsletter (aesop); stores and services (mejuri)",
      "A mode-flipped footer (aesop) or a calm text-led one (mejuri)",
    ],
    slugs: ["aesop", "gymshark", "mejuri"],
    caution: "Only with photography good enough to carry full-bleed acts (mejuri, gymshark); a smaller store keeps one hero, one or two product rows and one category band, and none of the urgency machinery (gymshark).",
  },
  {
    id: "values-and-locality",
    name: "Values and locality",
    when: "A recurring local service where the buyer cares who you are and whether you come to them.",
    steps: [
      "Values-and-place headline over warm photography, with a quote CTA (greenwise-organic-lawn-care)",
      "Why-choose reassurance band (greenwise-organic-lawn-care); benefit cards (block-renovation)",
      "Services overview (greenwise-organic-lawn-care); project types (block-renovation)",
      "Service-area cards with per-area contact (greenwise-organic-lawn-care); the city grid (block-renovation)",
      "Coverage checker: input, then personalise (greenwise-organic-lawn-care); see contractors and costs near you (block-renovation)",
      "A genuine story that makes the values credible (greenwise-organic-lawn-care)",
      "Quote form close (greenwise-organic-lawn-care); a confident closing CTA (block-renovation)",
      "Footer with services and service areas (greenwise-organic-lawn-care)",
    ],
    slugs: ["greenwise-organic-lawn-care", "block-renovation"],
    caution: "Lead with values and place, not price, and never claim values without a real story behind them (greenwise-organic-lawn-care).",
  },
  {
    id: "five-acts",
    name: "Five acts",
    when: "A service or consultancy selling judgement rather than features.",
    steps: ["State the position on the calmest canvas", "One flagship project given the whole stage, mode-flipped", "A small proof grid", "The mission repeated as a statement, no CTA", "A dark footer that weighs as much as the hero"],
    slugs: ["anthropic"],
    caution: "Each section has the budget of two; condensing without earning the weight reads as thin rather than minimal. Read from anthropic alone: setia-law and swillhouse were cited for it and their notes describe other orders.",
  },
  {
    id: "one-product-per-act",
    name: "One product per act",
    when: "An adviser or a multi-service firm.",
    steps: [
      "A warm hero (wealthsimple, avalon-accounting), or a problem question with an immediate capture (pilot-accounting)",
      "One service per act on alternating grounds (wealthsimple, pilot-accounting)",
      "A trust count (wealthsimple), a partner badge band (avalon-accounting), a logo strip in the first fold (pilot-accounting)",
      "A single clear CTA: a dark pill (wealthsimple) or a contact form (avalon-accounting)",
    ],
    slugs: ["wealthsimple", "pilot-accounting", "avalon-accounting"],
    caution: "A local adviser compresses to a warm hero, two or three acts, a trust block and a contact CTA; the ticker and the comparison tables are bank-scale (wealthsimple).",
  },
  {
    id: "paid-landing",
    name: "Paid landing",
    when: "A page carrying paid traffic to one offer, built the way attentive, mercury and pilot-accounting convert a cold click.",
    steps: [
      "Hero with the promise and the next step in it: an inline capture (mercury, pilot-accounting), or one or two actions over real-people photography (attentive)",
      "Trust directly beneath: a logo strip where the names are known (attentive, pilot-accounting), otherwise a count plus a character claim (mercury)",
      "The problem framed in the buyer's own terms (pilot-accounting)",
      "Feature deep-dives, each text plus a proof panel, one per act on alternating grounds (attentive, pilot-accounting)",
      "The process as a short step list where the buyer has to act (mercury)",
      "Real results as customer cards (attentive); a quantitative flex only where the numbers genuinely flex (mercury)",
      "A brand-voice positioning block that speaks to the buyer's identity rather than the product (mercury)",
      "Tiers as product cards (pilot-accounting)",
      "A closing call to action that echoes the hero's own control (attentive, mercury)",
    ],
    slugs: ["attentive", "mercury", "pilot-accounting"],
    caution: "Compress hard: pilot's is a forty-section enterprise page, and a local business keeps the problem hero, the proof, a few acts and one CTA; swap logos nobody recognises for accreditations that mean something to the audience (pilot-accounting). Do not ship twenty sections without genuine product depth (attentive).",
  },
  {
    id: "booking-first",
    name: "Booking first",
    when: "Class or appointment businesses: studios, clinics, salons.",
    steps: [
      "A hero that does discovery and booking together: a studio finder in the hero (barrys), BOOK NOW on the concept hero (unoit), the persistent book link in the ribbon (warby-parker)",
      "Trust directly beneath the hero (warby-parker)",
      "Alternate cinematic photographic bands with one or two bright human acts (barrys)",
      "Services as browsable expandable rows (unoit); product features alternating with service explainers (warby-parker)",
      "Locations, each with its own page, before the closing booking CTA (unoit)",
      "Community proof (barrys); a social-proof band (warby-parker)",
      "A warm closing booking CTA (unoit, barrys)",
    ],
    slugs: ["barrys", "warby-parker", "unoit"],
    caution: "Three to five bands for a single practice; the ten-band density belongs to a national retailer (warby-parker). The dark cinematic atmosphere only works with genuinely strong photography; lighten the palette rather than fake the mood (barrys).",
  },
];
