{{CLIENT_NAME}} Brand Assets — Licensing

The brand assets in this repository are the property of {{CLIENT_NAME}}.
Use is restricted to {{CLIENT_NAME}} and its authorised partners (including Jiffi).

PER-ASSET NOTES

Fonts:
{{FONT_LICENSES}}
<!-- e.g.
- BrandSans: licensed from {foundry}, desktop + web licence held by {{CLIENT_NAME}}.
- Adobe Fonts (if used): NOT redistributed. Kit ID {{KIT_ID}}. Consumers load via the Adobe kit.
-->

Logos, illustrations, characters: property of {{CLIENT_NAME}}.

Code (tokens, components, examples): MIT, generated by Jiffi for {{CLIENT_NAME}}.
