#!/usr/bin/env bash
# build-catalog-index.sh - regenerate CATALOG.md from the library data.
#
# CATALOG.md is the human / agent readable index of the library: every captured
# site grouped by style, plus the queue summary. It is GENERATED - never
# hand-edit it. Run this after adding or updating entries, before committing.
#
# Source of truth: each catalog/<slug>/tags.json + the "> Essence:" line of its
# overview.md, plus _meta/curation-queue.json. index.json stays the machine
# matrix; this is the readable view.
#
# Usage: build-catalog-index.sh        (uses JIFFI_REFERENCE_LIBRARY_PATH if set)
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB="${JIFFI_REFERENCE_LIBRARY_PATH:-${SCRIPT_DIR}/../references/reference-library}"
CATALOG="${LIB}/catalog"
QUEUE="${LIB}/_meta/curation-queue.json"
OUT="${LIB}/CATALOG.md"

[ -d "$CATALOG" ] || { echo "build-catalog-index: no catalog at ${CATALOG}" >&2; exit 1; }

emit() {
  echo "# Reference library catalog"
  echo
  echo "_Generated by \`scripts/build-catalog-index.sh\` - do not hand-edit._"
  echo
  echo "The human- and agent-readable index of the library. \`index.json\` is the"
  echo "machine matrix used by \`select-references.sh\`; this file is the readable"
  echo "view - every captured site grouped by style, with its one-line essence."
  echo

  local total=0 done=0
  for style in product service story operational consumer portfolio; do
    local rows=""
    for d in "$CATALOG"/*/; do
      local tg="${d}tags.json"
      [ -f "$tg" ] || continue
      local s; s=$(jq -r '.style // ""' "$tg" 2>/dev/null)
      [ "$s" = "$style" ] || continue
      local slug mode tier ess
      slug=$(jq -r '.site // ""' "$tg")
      mode=$(jq -r '.mode // ""' "$tg")
      tier=$(jq -r '.tier // "strong"' "$tg")
      ess=$(grep -m1 '^> Essence' "${d}overview.md" 2>/dev/null | sed 's/^> Essence:[[:space:]]*//')
      [ -z "$ess" ] && ess="_(deep notes pending)_"
      rows+="- **[${slug}](catalog/${slug}/)** &nbsp;\`${tier}\` \`${mode}\` - ${ess}"$'\n'
      total=$((total+1)); done=$((done+1))
    done
    if [ -n "$rows" ]; then
      echo "## ${style}"
      echo
      printf '%s\n' "$rows"
    fi
  done

  echo "## Curation queue"
  echo
  if [ -f "$QUEUE" ]; then
    local q qd qp
    q=$(jq '.queue | length' "$QUEUE" 2>/dev/null || echo 0)
    qd=$(jq '[.queue[] | select(.status=="done")] | length' "$QUEUE" 2>/dev/null || echo 0)
    qp=$(jq '[.queue[] | select(.status=="pending" or .status=="v1-migrate")] | length' "$QUEUE" 2>/dev/null || echo 0)
    echo "${q} sites in the queue - ${qd} done, ${qp} pending. Full list with"
    echo "categories and priorities in \`_meta/curation-queue.json\`."
  else
    echo "_No curation queue file found._"
  fi
  echo
  echo "_Captured entries above: ${done}._"
}

emit > "$OUT"
echo "build-catalog-index: wrote ${OUT}"
