#!/usr/bin/env bash
# scripts/palate-gitignore.sh - keep Palate's own working files out of the client's repo.
#
# ============================== WHY THIS EXISTS ==============================
#
# A real client build committed 387 of Palate's working files into the deliverable repo:
# 249 screenshots, the telemetry, the raw crawl. 297 MB. The scaffold shipped a .gitignore
# and it did not help, for two reasons that are both worth stating:
#
#   1. IT ONLY IGNORED TWO THINGS. `.palate/index.json` and `.palate/*.log`. Everything else
#      the build writes was committable, and `git add -A` duly added it.
#   2. IT LIVES IN THE WRONG PLACE FOR HALF THE LAYOUTS. The scaffold's .gitignore ships
#      inside `{slug}-site/`, and a build writes `.palate/`, `.palate-shots/` and
#      `build-manifest.json` at the WORKSPACE root, one level above it. When git is
#      initialised at the workspace root, the file cannot reach them.
#
# So the block lives HERE, once, and this script writes it wherever the repo actually is.
#
# THE RULE IT ENCODES: DERIVED state is ignored, MEASURED state is committed. Screenshots,
# telemetry, raw crawl output and logs can all be regenerated by re-running the tool.
# Baselines, the brand record, `assets.json` with its human review flags, the briefs and the
# donor lineage cannot: they record judgement and measurement that would be lost. Ignoring
# those would make every later contribution look like the first one.
#
# It is IDEMPOTENT (keyed on the marker), APPEND-ONLY (it never removes or rewrites a rule
# someone else put there), and silent unless it changes something. No repo, nothing to do.
#
# Usage: palate-gitignore.sh [dir]     (default: cwd)
set -euo pipefail

DIR="${1:-.}"
MARKER="# --- Palate working files (managed by palate-gitignore.sh; edit above this line) ---"

root="$(git -C "$DIR" rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "$root" ]; then
  # Not a git repo. That is normal early in a build and is not a problem to report: the
  # scaffold ships its own .gitignore, and this runs again once git init has happened.
  exit 0
fi

TARGET="$root/.gitignore"
if [ -f "$TARGET" ] && grep -qF "$MARKER" "$TARGET"; then
  exit 0
fi

# A trailing newline first, so appending to a file that does not end in one cannot glue the
# marker onto somebody's last rule.
[ -f "$TARGET" ] && [ -n "$(tail -c 1 "$TARGET" 2>/dev/null)" ] && printf '\n' >> "$TARGET"

cat >> "$TARGET" <<'IGNORE'

# --- Palate working files (managed by palate-gitignore.sh; edit above this line) ---
# DERIVED state: regenerated by re-running the tool, and large. A client build once
# committed 297 MB of this into its own deliverable repo.
build-manifest.json
build-manifest.json.*.json
.palate-skill-state.json
.palate-shots/
verify-report.json
.palate/index.json
.palate/*.log
.palate/*.backup.json
.palate/mcp-journal.jsonl
.palate/harvest/
.palate/live-capture/
.palate-devserver.log
.palate-devserver.pid

# MEASURED state stays COMMITTED and is deliberately NOT listed above: baselines, the brand
# record, assets.json (it carries the human review: which crop, which subject, what must not
# happen to a photo), the briefs, and the donor lineage. None of it can be recomputed, and
# without it every later contribution looks like the first one.
IGNORE

echo "palate: added the working-file ignores to $TARGET" >&2
