#!/usr/bin/env bash
# Tests the ignore rules for the working files that were NOT covered when a real adoption
# nearly committed 874 MB of screenshots.
#
# gitignore-leak.test.sh pins the original block (the build's own derived state). This pins
# what adoption, the scratch directory and Explore write, plus the case the original block
# could never reach: a repo that already carries the managed marker must GAIN a new rule,
# because a client repo adopted last month is exactly the repo about to commit the leak.
set -uo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
SCRIPT="$DIR/../palate-gitignore.sh"
SCAFFOLD_IGNORE="$DIR/../../templates/astro-project/.gitignore"
pass=0; fail=0
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
ok()  { echo "ok   - $1"; pass=$((pass+1)); }
bad() { echo "FAIL - $1"; fail=$((fail+1)); }

ignored() { git -C "$1" check-ignore -q "$2" 2>/dev/null && echo yes || echo no; }
expect() { # <desc> <repo> <path> <yes|no>
  local got; got=$(ignored "$2" "$3")
  [ "$got" = "$4" ] && ok "$1" || bad "$1 (ignored=$got, want $4)"
}

# The derived state that had no rule. Every one of these is regenerated by re-running a tool.
LEAKY=".palate/adoption/home-1440.png
.palate/adoption/routes/services-roofing.png
.palate/adoption/filmstrip/01.png
.palate/tmp/probe.json
src/pages/index.astro.palate-bak
public/_explore/b1-hero.png
.palate/explore/shots/b1-1440.png
.palate/explore/seed/canvas.json
.palate/explore/seed/README.md
.palate/explore/seed/Ref1.dc.html
.palate/explore/seed/ref1.jpg"

# MEASURED state in the same directories. Ignoring these is the opposite failure: the
# adoption record and the baselines are judgement, and cannot be recomputed.
# The Explore SEED artboards belong here too: they are hand-drawn, they are the record of the
# directions a client was shown, and `boards-render.mjs` validates them rather than writing
# them, so an ignore rule over the directory would drop the one artefact Explore produces.
KEEP=".palate/adoption/report.json
.palate/adoption/routes.json
.palate/baselines/home.json
.palate/assets.json
.palate/explore/seed/B1.dc.html
.palate/explore/seed/b1-hero.jpg
public/logo.png"

# ============ 1. THE WORKSPACE LAYOUT: the script writes the rules at the repo root ========
W="$TMP/work"; mkdir -p "$W"
git -C "$W" init -q 2>/dev/null
bash "$SCRIPT" "$W" >/dev/null 2>&1
while IFS= read -r f; do expect "root: $f is ignored" "$W" "$f" yes; done <<< "$LEAKY"
while IFS= read -r f; do expect "root: $f stays COMMITTED" "$W" "$f" no; done <<< "$KEEP"

# ============ 2. THE SITE LAYOUT: the scaffold's own .gitignore carries the same rules =====
S="$TMP/site"; mkdir -p "$S"
git -C "$S" init -q 2>/dev/null
cp "$SCAFFOLD_IGNORE" "$S/.gitignore"
while IFS= read -r f; do expect "scaffold: $f is ignored" "$S" "$f" yes; done <<< "$LEAKY"
while IFS= read -r f; do expect "scaffold: $f stays COMMITTED" "$S" "$f" no; done <<< "$KEEP"

# ============ 3. A REPO ADOPTED BEFORE THE RULE EXISTED must gain it ======================
# The marker made the script a no-op on any repo that already had the block, so every repo
# adopted before today would keep committing the screenshots this rule exists to stop.
O="$TMP/old"; mkdir -p "$O"
git -C "$O" init -q 2>/dev/null
cat > "$O/.gitignore" <<'OLD'
node_modules/

# --- Palate working files (managed by palate-gitignore.sh; edit above this line) ---
build-manifest.json
.palate-shots/
.palate/index.json
OLD
bash "$SCRIPT" "$O" >/dev/null 2>&1
expect "an already-managed repo gains the adoption rule" "$O" ".palate/adoption/home-1440.png" yes
expect "and the scratch rule"                            "$O" ".palate/tmp/probe.json" yes
expect "and keeps the rules it already had"              "$O" "build-manifest.json" yes
grep -q '^node_modules/$' "$O/.gitignore" && ok "and the client's own rule survives" \
  || bad "the client's own rule was lost"

# ============ 4. STILL IDEMPOTENT. A top-up must not run every time. ======================
before=$(wc -l < "$O/.gitignore")
bash "$SCRIPT" "$O" >/dev/null 2>&1
bash "$SCRIPT" "$O" >/dev/null 2>&1
after=$(wc -l < "$O/.gitignore")
[ "$before" = "$after" ] && ok "topping up twice adds nothing the second time" \
  || bad "the top-up repeats itself ($before -> $after lines)"

echo "---"
echo "passed=$pass failed=$fail"
[ "$fail" -eq 0 ]
